project:
  type: website
  output-dir: docs

website:
  title: "pi_makes"
  favicon: favicon.ico
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/alessio-pugliese
      - icon: twitter
        href: https://twitter.com/alessiop86
      - icon: mastodon
        href: https://mastodon.uno/@ale_pi
  page-footer: "©2022-2023, Alessio Pugliese" 
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

