project:
  type: website

website:
  title: "pi_makes"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/alessio-pugliese
      - icon: twitter
        href: https://twitter.com/alessiop86
      - icon: mastodon
        href: https://mastodon.uno/@ale_pi
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

